name: ðŸš€ Deploy website to DEV
on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore: [".vscode/**", "README.md", ".*"]
permissions:
  contents: write
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --configuration Debug --no-restore

      - name: ðŸ“‚ Upload files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: landmarkanalytics.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./bin/Debug/net6.0/publish/
          server-dir: ./dev.landmarkanalytics.com/
          protocol: ftps
          exclude: |
            .cspell.json
            package.json
            package-lock.json
